openapi: 3.0.1
info:
  title: BNG Update1 EXT API
  description: Update1 Test
  version: v1.0
servers:
  - url: https://dev-ext-api-gateway.azure.defra.cloud/BNGICC/v1.0
paths:
  /gainsite1:
    get:
      summary: gainsite1
      description: Test operation
      operationId: gainsite1
      responses:
        '200':
          description: ''
components: { }
