openapi: 3.0.1
info:
  title: BNG
  description: BNG
  version: '1.0'
servers:
  - url: https://dev-api-gateway.azure.defra.cloud/api/bng/v1
paths:
  '/gainsite/{GainSiteNumber}':
    get:
      summary: GainSites
      description: GainSites
      operationId: gainsites
      parameters:
        - name: GainSiteNumber
          in: path
          required: true
          schema:
            type: String
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]

