openapi: 3.0.1
info:
  title: BNGICC
  description: BNGICC
  version: '1.0'

servers:
  - url: https://devapiinfam2403.azure-api.net/api/bng-icc 

paths:
  '/gainsite/{GainSiteNumber}':
    get:
      summary: GainSites
      description: GainSites
      operationId: gainsites
      parameters:
        - name: GainSiteNumber
          in: path
          required: true
          schema:
            type: String
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
